name: semester_project_group_e

channels:
    - conda-forge
    - defaults

dependencies:
    - matplotlib==3.10.0
    - numpy==2.2.1
    - packaging==24.2
    - pandas==2.2.3
    - plotly==5.24.1
    - scikit_learn==1.6.0
    - seaborn==0.13.2
    - streamlit==1.41.1
    - streamlit_plotly_events==0.0.6
